name 'topology-truck'
maintainer 'John Sweitzer'
maintainer_email 'john_sweitzer@thirdwaveinsights.com'
license 'all_rights'
version '0.1.0'
issues_url 'https://github.com/john_sweitzer/topology-truck/issues'
source_url 'https://github.com/john_sweitzer/topology-truck'

depends 'delivery-truck'
depends 'delivery-sugar'
depends 'chef-sugar'
